apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chuchu
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chuchu
    spec:
      containers:
      - name: master
        image: gcr.io/cream-heros/chuchu:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-token
          mountPath: /etc/secret-token
        env:
        - name: CHUCHU_TOKEN_PATH
          value: /etc/secret-token/chuchu-token
      volumes:
      - name: secret-token
        secret:
          secretName: chuchu-token
