apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coco
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coco
    spec:
      containers:
      - name: master
        image: gcr.io/cream-heros/coco:v1
        imagePullPolicy: Always
        volumeMounts:
        - name: secret-token
          mountPath: /etc/secret-token
        env:
        - name: COCO_TOKEN_PATH
          value: /etc/secret-token/coco-token
      volumes:
      - name: secret-token
        secret:
          secretName: coco-token
