apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: momo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: momo
    spec:
      containers:
      - name: master
        image: gcr.io/cream-heros/momo:v1
        volumeMounts:
        - name: secret-token
          mountPath: /etc/secret-token
        env:
        - name: MOMO_TOKEN_PATH
          value: /etc/secret-token/momo-token
      volumes:
      - name: secret-token
        secret:
          secretName: momo-token
