apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tt
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tt
    spec:
      containers:
      - name: master
        image: gcr.io/cream-heros/tt:v1
        volumeMounts:
        - name: secret-token
          mountPath: /etc/secret-token
        env:
        - name: TT_TOKEN_PATH
          value: /etc/secret-token/tt-token
      volumes:
      - name: secret-token
        secret:
          secretName: tt-token
