apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lulu
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lulu
    spec:
      containers:
      - name: master
        image: gcr.io/cream-heros/lulu:v1
        volumeMounts:
        - name: secret-token
          mountPath: /etc/secret-token
        env:
        - name: LULU_TOKEN_PATH
          value: /etc/secret-token/lulu-token
      volumes:
      - name: secret-token
        secret:
          secretName: lulu-token
